[package]
name = "hello-rocket"
version = "0.1.0"
authors = ["NEUZhangy <alice7neusoft1207@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.4.7"
rand = "0.8.3"